name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: npm run build

      # ===== Clave SSH SIN base64 =====
      - name: Prepare SSH key (no base64)
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          umask 077
          # Guardamos la clave en archivo
          printf '%s' "$SSH_KEY" > id_ed25519
          # Normalizamos fin de línea por si vino de Windows
          sed -i 's/\r$//' id_ed25519
          chmod 600 id_ed25519

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Upload project to server
        run: |
          rsync -az --delete \
            -e "ssh -i id_ed25519" \
            --exclude ".git" --exclude "node_modules" --exclude ".github" \
            --exclude ".env*" \
            ./  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.APP_DIR }}/

      - name: Install & restart on server
        run: |
          ssh -i id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -euo pipefail
            cd "${APP_DIR}"
            npm ci
            npm run build
            pm2 startOrReload ecosystem.config.js --update-env
            pm2 save
          EOF
        env:
          APP_DIR: ${{ secrets.APP_DIR }}
